export const CONNECTION = 'connection'
export const DISCONNECT = 'disconnect'
export const NEW_PLAYER = 'NEW_PLAYER'
export const JOIN_GAME = 'JOIN_GAME'
export const SERVER_INFO = 'SERVER_INFO'
export const CREATE_GAME = 'CREATE_GAME'
export const GAME_JOINED = 'GAME_JOINED'
